#    mqtt: docker run -d -p 1883:1883  leojrfs/mosq
mqtt:
        build: mqtt
        ports:
                - "1883:1883"
        restart: "always"
nodered:
        image: nodered/node-red-docker:rpi
        ports:
                - "1880:1880"
        links:
                - "mqtt"
        volumes:
                - "./nodered/data/flows.json:/data/flows.json"
        restart: "always"

